version: 0.0
os: linux

files:
  - source: application-code/
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/docker_build.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/docker_run.sh
      timeout: 300
      runas: root
