version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo Building frontend...
      - cd ../../application-code/web-tier/Dockerfile
      - Docker build -t webapp .
      - echo Build complete.
